<?php
// TODO: inserire la città nell'indirizzo

return  [
  [
    "name"=> "Sea La Vie",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "https://cf.bstatic.com/xdata/images/hotel/max1024x768/95862692.jpg?k=1f15546fa1d4e9a739df5c3393a530f1539e2c4819593a6326c3113410f58794&o=&hp=1",
    "address"=> "via della fontana, 51, 48122, Punta Marina RA",
    "address_info"=> "Dicta autem molestiae necessitatibus et.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Aspen Glow",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "https://www.immobiliare.it/news/app/uploads/2022/01/montagna-baita_seconda_casa_neve_chalet_min.jpeg",
    "address"=> "Rotonda Nestore 15 10052 Bardonecchia TO",
    "address_info"=> "A aliquid consequuntur nemo velit laudantium facilis.",
    "price"=> "68.99",
    "n_of_bed"=> "2",
    "n_of_room"=> "1",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "48 m2",
    "visible"=> false,
    "type"=> "bilocale"
  ],
  [
    "name"=> "The Orchard",
    "description"=> "Villa di lusso",
    "cover_image"=> "https://media.agestaweb.it/siti/01171/public/foto/1(150).jpg",
    "address"=> "Via Bianco 792 Piano 5",
    "address_info"=> "Veritatis libero laboriosam impedit.",
    "price"=> "298.75",
    "n_of_bed"=> "8",
    "n_of_room"=> "3",
    "n_of_bathroom"=> "3",
    "apartmen_size"=> "150 m2",
    "visible"=> false,
    "type"=> "quadrilocale"
  ],
  [
    "name"=> "Eco Stay",
    "description"=> "Appartamento in centro",
    "cover_image"=> "https://www.bolognare.it/wp-content/uploads/603724.jpg",
    "address"=> "Via Vittor Pisani, 1, 20124 Milano MI",
    "address_info"=> "Impedit voluptatum placeat ut.",
    "price"=> "120.89",
    "n_of_bed"=> "1",
    "n_of_room"=> "1",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "30 m2",
    "visible"=> false,
    "type"=> "monolocale"
  ],
  [
    "name"=> "Rhapsody by the Sea",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "https://hips.hearstapps.com/hmg-prod/images/kralendjik-1-caraibi-1553763129.jpg",
    "address"=> "Via Posillipo-36B-80123-Napoli-NA",
    "address_info"=> "Unde aut architecto et.",
    "price"=> "79.99",
    "n_of_bed"=> "3",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "2",
    "apartmen_size"=> "54 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Forrest Creek",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "https://media.lavorincasa.it/post/16/15504/gallery/6242/casa-in-montagna-moderna-da-pinterest.jpg",
    "address"=> "28841 Provincia del Verbano-Cusio-Ossola",
    "address_info"=> "Dicta ut et dolorem ut ab.",
    "price"=> "109.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "74 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Oak View",
    "description"=> "Villa di lusso",
    "cover_image"=> "https://jacopotartaglia.it/wp-content/uploads/2021/06/webaliser-_TPTXZd9mOo-unsplash.jpg",
    "address"=> "Via IV Novembre 16d 40123 Bologna ",
    "address_info"=> "Cum qui aspernatur earum nemo tempore aut aut qui.",
    "price"=> "289.99",
    "n_of_bed"=> "6",
    "n_of_room"=> "3",
    "n_of_bathroom"=> "2",
    "apartmen_size"=> "154 m2",
    "visible"=> false,
    "type"=> "quadrilocale"
  ],
  [
    "name"=> "The View",
    "description"=> "Appartamento in centro",
    "cover_image"=> "https://img3.idealista.it/blur/WEB_LISTING-M/0/id.pro.it.image.master/3b/1a/3b/471780604.jpg",
    "address"=> "Incrocio Marini 2 Appartamento 09",
    "address_info"=> "Quis voluptatem id temporibus maxime nostrum.",
    "price"=> "49.99",
    "n_of_bed"=> "2",
    "n_of_room"=> "1",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "54 m2",
    "visible"=> false,
    "type"=> "bilocale"
  ],
  [
    "name"=> "Beachy Vibes",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "https://www.pugliacasevacanza.com/img/case-vacanza/182/1.jpg",
    "address"=> "73028 Otranto LE",
    "address_info"=> "Consequatur sed debitis non eveniet natus ab ut.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Daffodil Hill",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "https://news.wikicasa.it/wp-content/uploads/2021/11/Progetto-senza-titolo-30__-1-1024x672.jpg",
    "address"=> "23041 Livigno SO",
    "address_info"=> "Enim sunt nulla ut itaque repellat ab.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Sierra Sky",
    "description"=> "Villa di lusso",
    "cover_image"=> "https://www.villeecasali.com/wp-content/uploads/2017/01/Una-villa-da-250-milioni-1-1024x576.jpg",
    "address"=> "Piazza di Santa Maria Nuova, 1, 50122 Firenze FI",
    "address_info"=> "Aliquid qui repellendus fugiat architecto eius.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "The Retreat",
    "description"=> "Appartamento in centro",
    "cover_image"=> "https://img3.idealista.it/blur/WEB_LISTING-M/0/id.pro.it.image.master/03/ed/7d/464631295.jpg",
    "address"=> "Marghera, Venezia VE",
    "address_info"=> "Ea sed exercitationem aut velit corrupti cumque repellendus.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Castaway",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "https://www.casevacanzepomelia.it/imga/aurora-villa-sulla-spiaggia-di-sabbia-vicino-marzamemi---cir-19089014c217434-panoramica--6477--1500.jpg",
    "address"=> "89866 Gurdurello VV",
    "address_info"=> "In veritatis inventore incidunt vitae hic sit nisi placeat.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "The Golden Eagle",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "https://blog.quimmo.it/wp-content/uploads/2018/10/comprare-una-casa-in-montagna-768x510.jpg",
    "address"=> "Rotonda Flaviana 36 39040 Racines BZ",
    "address_info"=> "Nisi qui voluptates tempora aut.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Moon Dunes",
    "description"=> "Villa di lusso",
    "cover_image"=> "https://cdn.cw-ibiza.it/upload/Luxury-Villas-Ibiza-for-sale-00.jpg",
    "address"=> "Via di Villa Ruffo, 5, 00196 Roma RM",
    "address_info"=> "Ut omnis incidunt rerum doloremque expedita consequuntur.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Parkview Living",
    "description"=> "Appartamento in centro",
    "cover_image"=> "https://pwm.im-cdn.it/image/1312668240/m-c.jpg",
    "address"=> "Str. Vicinale Francescone, 19, 65125 Pescara PE",
    "address_info"=> "Doloremque quibusdam numquam aliquid esse.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Cabana",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSF-BwLEbXqvfqMWtizUVwYK0mXU4bgbUnSg&usqp=CAU",
    "address"=> "90010 Campofelice di Roccella PA",
    "address_info"=> "Vel deserunt alias quam beatae incidunt numquam qui illum.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Summit Watch",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "https://cdn.trend-online.com/2022/11/21/812301/full.webp",
    "address"=> "87066 Longobucco CS",
    "address_info"=> "Culpa quibusdam possimus architecto ut corporis sit.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "Dreamsville",
    "description"=> "Villa di lusso",
    "cover_image"=> "https://i.pinimg.com/originals/5b/bf/57/5bbf5746e2a1add8256edf0337443e9e.jpg",
    "address"=> "Via Arenaccia, 135, 80141 Napoli NA",
    "address_info"=> "Dicta ea sint tempora illum architecto fugit nisi.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ],
  [
    "name"=> "The Breeze Way",
    "description"=> "Appartamento in centro",
    "cover_image"=> "https://pwm.im-cdn.it/image/1109155996/cover-m-c.jpg",
    "address"=> "Via Salvatore Matarrese, 45, 70124 Bari BA",
    "address_info"=> "Veniam qui minima sapiente sit sit neque laborum.",
    "price"=> "89.99",
    "n_of_bed"=> "4",
    "n_of_room"=> "2",
    "n_of_bathroom"=> "1",
    "apartmen_size"=> "64 m2",
    "visible"=> false,
    "type"=> "trilocale"
  ]
];
