<?php

return  [
  [
    "name"=> "Sea La Vie",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/1.jpg",
    "address"=> "via della fontana, 51, 48122, Punta Marina RA",
    "address_info"=> "Procedi lungo la via della fontana fino a quando raggiungi il civico 51, che sarà sulla tua sinistra. È una casa a due piani con una porta blu.",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Aspen Glow",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/2.jpg",
    "address"=> "Rotonda Nestore 15 10052 Bardonecchia TO",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 2,
    "n_of_room"=> 1,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Orchard",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/3.jpg",
    "address"=> "Via mario Bianco 75 Bergamo",
    "address_info"=> "Inizia dalla Via mario Bianco e cammina verso sud fino a trovare il numero civico 75. La casa è una villa bianca con un grande giardino.",
    "price"=> rand(30,150),
    "n_of_bed"=> 8,
    "n_of_room"=> 3,
    "n_of_bathroom"=> 3,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Eco Stay",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/4.jpg",
    "address"=> "Via Vittor Pisani, 1, 20124 Milano MI",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 1,
    "n_of_room"=> 1,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Rhapsody by the Sea",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/5.jpg",
    "address"=> "Via Posillipo-36B-80123-Napoli-NA",
    "address_info"=> "Percorri Via Posillipo fino a quando raggiungi il numero 36. La casa è l'ultima sulla destra, con un cancello di ferro verde e una facciata color crema.",
    "price"=> rand(30,150),
    "n_of_bed"=> 3,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 2,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Forrest Creek",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/6.jpg",
    "address"=> "28841 Provincia del Verbano-Cusio-Ossola",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Oak View",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/7.jpg",
    "address"=> "Via IV Novembre 16d 40123 Bologna ",
    "address_info"=> "Segui la Via IV Novembre finché non raggiungi il numero civico 16, che sarà sulla tua sinistra. La casa è una cascina rossa con un tetto di tegole.",
    "price"=> rand(30,150),
    "n_of_bed"=> 6,
    "n_of_room"=> 3,
    "n_of_bathroom"=> 2,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The View",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/8.jpg",
    "address"=> "28925 Via Marini 20 Pallanza",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 2,
    "n_of_room"=> 1,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Beachy Vibes",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/9.jpg",
    "address"=> "73028 Otranto LE",
    "address_info"=> "Prendi Viale dei Pini e prosegui fino al civico 12, che troverai sulla tua destra. La casa è un'accogliente villetta gialla con un piccolo portico",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Daffodil Hill",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/10.jpg",
    "address"=> "23041 Livigno SO",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Sierra Sky",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/11.jpg",
    "address"=> "Piazza di Santa Maria Nuova, 1, 50122 Firenze FI",
    "address_info"=> "Segui Piazza di Santa Maria Nuova fino a raggiungere il numero 1. La casa è un appartamento al secondo piano di un edificio con mattoni a vista.",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Retreat",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/12.jpg",
    "address"=> "Marghera, Venezia VE",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Castaway",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/13.jpg",
    "address"=> "89866 Gurdurello VV",
    "address_info"=> "Cammina lungo Corso Italia fino a quando raggiungi il civico 30, che sarà sulla tua sinistra. La casa è un palazzo d'epoca con una balconata in ferro battuto.",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Golden Eagle",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/14.jpg",
    "address"=> "Rotonda Flaviana 36 39040 Racines BZ",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Moon Dunes",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/15.jpg",
    "address"=> "Via di Villa Ruffo, 5, 00196 Roma RM",
    "address_info"=> "Percorri Via di Villa Ruffo fino a trovare il numero civico 5 sulla tua destra. La casa è una villa moderna con un giardino ben curato.",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Parkview Living",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/16.jpg",
    "address"=> "Str. Vicinale Francescone, 19, 65125 Pescara PE",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Cabana",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/17.jpg",
    "address"=> "90010 Campofelice di Roccella PA",
    "address_info"=> "Inizia da Piazza Mazzini e cerca il numero 3. La casa è un vecchio casolare in mattoni con una porta verde e un tetto di paglia.",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Summit Watch",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/18.jpg",
    "address"=> "87066 Longobucco CS",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Dreamsville",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/19.jpg",
    "address"=> "Via Arenaccia, 135, 80141 Napoli NA",
    "address_info"=> "Segui Via Arenaccia fino a raggiungere il civico 135, che troverai sulla tua destra. La casa è un grazioso cottage rosa con una veranda fiorita.

    ",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Breeze Way",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/20.jpg",
    "address"=> "Via Salvatore Matarrese, 45, 70124 Bari BA",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> 4,
    "n_of_room"=> 2,
    "n_of_bathroom"=> 1,
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "services"=> [1,2,5,7]
  ]
];
