<?php

return  [
  [
    "name"=> "Sea La Vie",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/1.jpg",
    "address"=> "via della fontana, 51, 48122, Punta Marina RA",
    "address_info"=> "Procedi lungo la via della fontana fino a quando raggiungi il civico 51, che sarà sulla tua sinistra. È una casa a due piani con una porta blu.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Aspen Glow",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/2.jpg",
    "address"=> "Rotonda Nestore 15 10052 Bardonecchia TO",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Orchard",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/3.jpg",
    "address"=> "Via mario Bianco 75 Bergamo",
    "address_info"=> "Inizia dalla Via mario Bianco e cammina verso sud fino a trovare il numero civico 75. La casa è una villa bianca con un grande giardino.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Eco Stay",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/4.jpg",
    "address"=> "Via Vittor Pisani, 1, 20124 Milano MI",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Rhapsody by the Sea",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/5.jpg",
    "address"=> "Via Posillipo-36B-80123-Napoli-NA",
    "address_info"=> "Percorri Via Posillipo fino a quando raggiungi il numero 36. La casa è l'ultima sulla destra, con un cancello di ferro verde e una facciata color crema.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Forrest Creek",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/6.jpg",
    "address"=> "28841 Provincia del Verbano-Cusio-Ossola",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Oak View",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/7.jpg",
    "address"=> "Via IV Novembre 16d 40123 Bologna ",
    "address_info"=> "Segui la Via IV Novembre finché non raggiungi il numero civico 16, che sarà sulla tua sinistra. La casa è una cascina rossa con un tetto di tegole.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The View",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/8.jpg",
    "address"=> "28925 Via Marini 20 Pallanza",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Beachy Vibes",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/9.jpeg",
    "address"=> "73028 Otranto LE",
    "address_info"=> "Prendi Viale dei Pini e prosegui fino al civico 12, che troverai sulla tua destra. La casa è un'accogliente villetta gialla con un piccolo portico",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Daffodil Hill",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/10.jpg",
    "address"=> "23041 Livigno SO",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Sierra Sky",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/11.jpg",
    "address"=> "Piazza di Santa Maria Nuova, 1, 50122 Firenze FI",
    "address_info"=> "Segui Piazza di Santa Maria Nuova fino a raggiungere il numero 1. La casa è un appartamento al secondo piano di un edificio con mattoni a vista.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Retreat",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/12.jpg",
    "address"=> "Marghera, Venezia VE",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Castaway",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/13.jpeg",
    "address"=> "89866 Gurdurello VV",
    "address_info"=> "Cammina lungo Corso Italia fino a quando raggiungi il civico 30, che sarà sulla tua sinistra. La casa è un palazzo d'epoca con una balconata in ferro battuto.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Golden Eagle",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/14.jpg",
    "address"=> "Rotonda Flaviana 36 39040 Racines BZ",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Moon Dunes",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/15.jpg",
    "address"=> "Via di Villa Ruffo, 5, 00196 Roma RM",
    "address_info"=> "Percorri Via di Villa Ruffo fino a trovare il numero civico 5 sulla tua destra. La casa è una villa moderna con un giardino ben curato.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Parkview Living",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/16.jpg",
    "address"=> "Str. Vicinale Francescone, 19, 65125 Pescara PE",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Cabana",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/17.jpeg",
    "address"=> "90010 Campofelice di Roccella PA",
    "address_info"=> "Inizia da Piazza Mazzini e cerca il numero 3. La casa è un vecchio casolare in mattoni con una porta verde e un tetto di paglia.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Summit Watch",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/18.jpg",
    "address"=> "87066 Longobucco CS",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Dreamsville",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/19.jpg",
    "address"=> "Via Arenaccia, 135, 80141 Napoli NA",
    "address_info"=> "Segui Via Arenaccia fino a raggiungere il civico 135, che troverai sulla tua destra. La casa è un grazioso cottage rosa con una veranda fiorita.

    ",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "The Breeze Way",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/20.jpg",
    "address"=> "Via Salvatore Matarrese, 45, 70124 Bari BA",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "bilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa del Sole",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/21.jpg",
    "address"=> "Viale della Resistenza, 13/D, 07041 Alghero SS",
    "address_info"=> "L'indirizzo si trova a Alghero, in Sardegna. È raggiungibile tramite Viale della Resistenza, numero civico 13/D. Il codice postale è 07041 e la sigla della provincia è SS.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Quercia",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/22.jpg",
    "address"=> "Bardonecchia, 10052 TO",
    "address_info"=> "",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Attico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Aurora",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/23.jpg",
    "address"=> "Corso Bramante, 53, 10126 Torino TO",
    "address_info"=> "Il Corso Bramante si trova nel quartiere di Crocetta, una zona residenziale di Torino. È facilmente raggiungibile tramite i mezzi pubblici, come l'autobus e la metropolitana, con la fermata più vicina a circa 500 metri di distanza.",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Villa",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Bella",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/24.jpg",
    "address"=> "Via Errico Petrella, 21, 20124 Milano MI",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Loft",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Casetta",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/25.jpeg",
    "address"=> "Via del Mare, 1, Rimini (RN)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Mansarda",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Verde",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/26.jpg",
    "address"=> "10151 Via Roma 1, Cervinia (AO)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Rustico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa dei Fiori",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/27.jpg",
    "address"=> "Roma - 00100 Via del Corso",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Mia",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/28.jpg",
    "address"=> "Milano - 20121 Via Montenapoleone",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Studio",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Torretta",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/29.jpeg",
    "address"=> "Lungomare di Ponente, 10, Riccione (RN)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Bungalow",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Paradiso",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/30.jpg",
    "address"=> "11020 Via Monte Bianco 23, Courmayeur (AO)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Chalet",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Rosa",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/31.jpg",
    "address"=> "Napoli - 80100 Via Toledo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Serenità",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/32.jpg",
    "address"=> "Torino - 10121 Via Roma",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Loft",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Cascina",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/33.jpeg",
    "address"=> "Viale Italia, 20, Cesenatico (FC)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa del Bosco",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/34.jpg",
    "address"=> "22013 Via Monte Rosa 5, Domodossola (VB)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Attico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa del Lago",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/35.jpeg",
    "address"=> "Firenze - 50100 Via dei Calzaiuoli",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La casa Bianca",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/36.jpg",
    "address"=> "Venezia - 30121 Calle Larga XXII Marzo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Studio",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Dolce Vita",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/37.jpeg",
    "address"=> "Via Lungomare, 30, Cattolica (RN)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Montagna",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/38.jpg",
    "address"=> "24010 Via Adamello 10, Clusone (BG)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Rustico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Romantica",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/39.jpg",
    "address"=> "Verona - 37121 Via Mazzini",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Amore",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/40.jpg",
    "address"=> "Bologna - 40121 Piazza Maggiore",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Attico",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa del Mare",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/41.jpeg",
    "address"=> "Piazza Milano, 2, Milano Marittima (RA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Bilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Dimora",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/42.jpg",
    "address"=> "32041 Via Catinaccio 7, Auronzo di Cadore (BL)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Chalet",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Corte",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/43.jpg",
    "address"=> "Genova - 16121 Via Garibaldi",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Villa",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Felice",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/44.jpg",
    "address"=> "Palermo - 90100 Corso Vittorio Emanuele",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Bungalow",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Dei Sogni",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/45.jpeg",
    "address"=> "Corso Italia, 15, Bibione (VE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Studio",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa degli Angeli",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/46.jpg",
    "address"=> "36016 Via Pale di San Martino 8, Canazei (TN)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Tranquilla",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/47.jpg",
    "address"=> "Padova - 35121 Via del Santo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casa di Pietra",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/48.jpg",
    "address"=> "Bari - 70121 Corso Cavour",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa Panorama",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/49.jpeg",
    "address"=> "Via Lungomare, 40, Jesolo (VE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Mansarda",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa di Campagna",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/50.jpg",
    "address"=> "39048 Via Ortles 12, Selva di Val Gardena (BZ)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Rustico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa dei Cigni",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/51.jpg",
    "address"=> "Catania - 95100 Via Etnea",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa dei Ricordi",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/52.jpg",
    "address"=> "Cagliari - 09100 Via Roma",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Attico",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Colonica",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/53.jpeg",
    "address"=> "Lungomare Adriatico, 25, Pesaro (PU)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Stella",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/54.jpg",
    "address"=> "43038 Via Cimone 15, Sillano (PR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Chalet",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Sogno",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/55.jpg",
    "address"=> "Trieste - 34121 Piazza Unità d'Italia",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Villa",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casetta Rossa",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/56.jpg",
    "address"=> "Perugia - 06123 Corso Vannucci",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Loft",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Primavera",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/57.jpeg",
    "address"=> "Viale della Vittoria, 35, Senigallia (AN)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Studio",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa dei Girasoli",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/58.jpg",
    "address"=> "44020 Via Monte Cimone 4, Sestola (MO)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Villetta",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/59.jpg",
    "address"=> "Ravenna - 48121 Via Cavour",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa del Cuore",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/60.jpg",
    "address"=> "Modena - 41121 Corso Duomo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Casina Blu",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/61.jpeg",
    "address"=> "Via Lungomare, 50, Fano (PU)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Mansarda",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa del Silenzio",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/62.jpg",
    "address"=> "48033 Via Gran Sasso 6, Prato (RA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Rustico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Fiorita",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/63.jpg",
    "address"=> "Parma - 43121 Piazza Garibaldi",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Aurora",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/64.jpg",
    "address"=> "Bergamo - 24121 Via XX Settembre",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Attico",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Casa dei Limoni",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/65.jpeg",
    "address"=> "Corso Colombo, 5, Ancona (AN)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Trilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Rustica",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/66.jpg",
    "address"=> "53021 Via Corno alle Scale 9, Abetone (PT)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Chalet",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa delle Rose",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/67.jpg",
    "address"=> "Pisa - 56125 Via Santa Maria",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Villa",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Dimora dei Sogni",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/68.jpg",
    "address"=> "Livorno - 57121 Piazza Grande",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Loft",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Azzurra",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/69.jpeg",
    "address"=> "Lungomare Europa, 55, Pescara (PE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Studio",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Natura",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/70.jpg",
    "address"=> "58010 Via Monte Amiata 3, Campagnatico (GR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa del Vino",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/71.jpg",
    "address"=> "Arezzo - 52100 Corso Italia",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Appartamento duplex",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casa delle Farfalle",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/72.jpg",
    "address"=> "Lucca - 55100 Via Fillungo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Monolocale",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa Armonia",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/73.jpeg",
    "address"=> "Via Lungomare, 60, Montesilvano (PE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Mansarda",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa del Prato",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/74.jpg",
    "address"=> "61028 Via Monte Nerone 11, Pergola (PU)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Rustico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Tenuta",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/75.jpg",
    "address"=> "Treviso - 31100 Piazza dei Signori",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Luna",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/76.jpg",
    "address"=> "Udine - 33100 Via Mercatovecchio",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Attico",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Cielo",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/77.jpeg",
    "address"=> "Lungomare Trieste, 45, Termoli (CB)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Bilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa dei Pini",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/78.jpg",
    "address"=> "64018 Via Velino 8, Castel del Monte (TE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Rustico",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa del Paradiso",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/79.jpg",
    "address"=> "Siracusa - 96100 Corso Matteotti",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Quadrilocale",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Incanto",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/80.jpg",
    "address"=> "Salerno - 84121 Corso Vittorio Emanuele",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Bungalow",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa Oasi",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/81.jpeg",
    "address"=> "Piazza Marconi, 8, Vieste (FG)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Studio",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Panoramica",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/82.jpg",
    "address"=> "66010 Via Maiella 22, Roccamorice (PE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Chalet",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Magica",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/83.jpg",
    "address"=> "Taranto - 74100 Via Duomo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Villa",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casina Gialla",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/84.jpg",
    "address"=> "Pescara - 65121 Corso Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "Loft",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa del Vento",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/85.jpeg",
    "address"=> "Viale Europa, 75, Bari (BA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Dimora d'Oro",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/86.jpg",
    "address"=> "67021 Via Sibillini 1, Amatrice (RI)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Serata",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/87.jpg",
    "address"=> "Sassari - 07100 Viale Italia
    ",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa del Fuoco",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/88.jpg",
    "address"=> "Ancona - 60121 Corso Mazzini",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Allegria",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/89.jpeg",
    "address"=> "Via Lungomare, 70, Polignano a Mare (BA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casetta dei Gelsomini",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/90.jpg",
    "address"=> "69048 Via Pollino 18, Rotonda (PZ)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Luminosa",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/91.jpg",
    "address"=> "Ferrara - 44121 Corso Ercole I d'Este",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Residenza",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/92.jpg",
    "address"=> "La Spezia - 19121 Via del Prione",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa del Mare",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/93.jpeg",
    "address"=> "Corso Vittorio Emanuele, 25, Monopoli (BA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casa della Luna Piena",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/94.jpg",
    "address"=> "71035 Via Alburni 27, Tramutola (PZ)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa del Castello",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/95.jpg",
    "address"=> "Rimini - 47921 Piazzale Federico Fellini",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Paradiso Perduto",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/96.jpg",
    "address"=> "Como - 22100 Via Vittorio Emanuele II",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa del Sole Nascente",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/97.jpeg",
    "address"=> "Lungomare di Levante, 80, Brindisi (BR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Sussurri",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/98.jpg",
    "address"=> "73010 Via Gargano 34, Vieste (FG)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa delle Perle",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/99.jpg",
    "address"=> "Monza - 20900 Via Vittorio Emanuele II",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa di Gloria",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/100.jpg",
    "address"=> "Latina - 04100 Corso della Repubblica",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Casetta dei Ricordi",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/101.jpeg",
    "address"=> "Viale Bari, 30, Ostuni (BR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa del Rifugio",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/102.jpg",
    "address"=> "75025 Via Monti della Laga 2, Castel Castagna (TE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa degli Uccelli",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/103.jpg",
    "address"=> "Cosenza - 87100 Corso Mazzini",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa d'Artista",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/104.jpg",
    "address"=> "Grosseto - 58100 Via Emilia",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Locus Amoenus",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/105.jpeg",
    "address"=> "Via Lungomare, 90, Taranto (TA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casa del Boschetto",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/106.jpg",
    "address"=> "76011 Via Pollino 12, Tricarico (MT)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Fiory",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/107.jpg",
    "address"=> "Brindisi - 72100 Corso Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Airone",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/108.jpg",
    "address"=> "Viterbo - 01100 Corso Italia
    ",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Ideale",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/109.jpeg",
    "address"=> "Lungomare Regina Margherita, 100, Gallipoli (LE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa delle Emozioni",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/110.jpg",
    "address"=> "80045 Via Vesuvio 20, Pompei (NA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Dimora degli Ulivi",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/111.jpg",
    "address"=> "Novara - 28100 Corso della Vittoria",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casa dei Colori",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/112.jpg",
    "address"=> "Asti - 14100 Corso Alfieri",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa del Porto",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/113.jpeg",
    "address"=> "Piazza del Ponente, 12, Porto Cesareo (LE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "La Casina del Bosco",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/114.jpg",
    "address"=> "82026 Via Matese 18, San Gregorio Matese (CE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa dei Sensi",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/115.jpg",
    "address"=> "Siena - 53100 Via di Città",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Relax",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/116.jpg",
    "address"=> "Matera - 75100 Via del Corso",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa del Tramonto",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/117.jpeg",
    "address"=> "Via Lungomare, 110, Lecce (LE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Appennino",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/118.jpg",
    "address"=> "84010 Via Cilento 9, Ascea (SA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa del Laghetto",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/119.jpg",
    "address"=> "Alessandria - 15121 Corso Roma",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Calma",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/120.jpg",
    "address"=> "Verbania - 28921 Corso Mameli",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "La Casetta dei Sogni",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/121.jpeg",
    "address"=> "Corso Umberto I, 16, Otranto (LE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Rifugio Alpino",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/122.jpg",
    "address"=> "86081 Via Pollino 6, Scanno (AQ)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Verde",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/123.jpg",
    "address"=> "Piacenza - 29121 Corso Vittorio Emanuele II",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Appartamento Città",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/124.jpg",
    "address"=> "Pesaro - 61121 Corso XI Settembre",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa Marina",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/125.jpeg",
    "address"=> "Lungomare Matteotti, 120, Santa Maria di Leuca (LE)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Chalet Aurora",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/126.jpg",
    "address"=> "87061 Via Sila 14, Camigliatello Silano (CS)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Rustico Campagna",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/127.jpg",
    "address"=> "Volterra - 56048 Via Porta all'Arco",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Loft Urbano",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/128.jpg",
    "address"=> "Sondrio - 23100 Corso Italia",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Blu",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/129.jpeg",
    "address"=> "Viale Roma, 40, Pizzo (VV)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Neve",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/130.jpg",
    "address"=> "88069 Via Aspromonte 3, Marina di Gioiosa Jonica (RC)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Fattoria del Sole",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/131.jpg",
    "address"=> "Varese - 21100 Corso Matteotti",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Dimora Storica",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/132.jpg",
    "address"=> "Benevento - 82100 Corso Garibaldi",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Loft Oceano",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/133.jpeg",
    "address"=> "Via Lungomare, 130, Tropea (VV)
    ",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Baita del Bosco",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/134.jpg",
    "address"=> "90046 Via Madonie 7, Petralia Sottana (PA)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Vigneto",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/135.jpg",
    "address"=> "Rieti - 02100 Corso Carbonari",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Villa Centro",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/136.jpg",
    "address"=> "Campobasso - 86100 Corso Vittorio Emanuele II",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Dimora Mare",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/137.jpeg",
    "address"=> "Lungomare Falcomatà, 150, Reggio Calabria (RC)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Monte",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/138.jpg",
    "address"=> "93018 Via Nebrodi 25, San Fratello (ME)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Agriturismo Terra",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/139.jpg",
    "address"=> "Frosinone - 03100 Corso della Repubblica",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Loft Moderno",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/140.jpg",
    "address"=> "Vigevano - 27029 Corso Milano",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Appartamento Acqua",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/141.jpeg",
    "address"=> "Lungomare Matteotti, 160, Villa San Giovanni (RC)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Chalet Panorama",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/142.jpg",
    "address"=> "95024 Via Etna 33, Linguaglossa (CT)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Cottage Collina",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/143.jpg",
    "address"=> "Potenza - 85100 Corso Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Centro",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/144.jpg",
    "address"=> "Crotone - 88900 Corso Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Cottage Spiaggia",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/145.jpeg",
    "address"=> "Corso Garibaldi, 20, Messina (ME)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Rustico Alpino",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/146.jpg",
    "address"=> "97018 Via Iblei 11, Modica (RG)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Dimora Campi",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/147.jpg",
    "address"=> "Sanremo - 18038 Corso Matteotti",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Residenza Prestige",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/148.jpg",
    "address"=> "Gela - 93012 Corso Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Casa Tramonto",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/149.jpeg",
    "address"=> "Via Lungomare, 170, Taormina (ME)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casetta Dolomiti",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/150.jpg",
    "address"=> "98024 Via Peloritani 29, Letojanni (ME)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casale Toscano",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/151.jpg",
    "address"=> "Lecce - 73100 Via Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Attico Metropolitan",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/152.jpg",
    "address"=> "Giardini-Naxos - 98035 Via Tysandros",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Villa Smeraldo",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/153.jpeg",
    "address"=> "Lungomare Giardina, 180, Giardini Naxos (ME)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Lodge Alpino",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/154.jpg",
    "address"=> "00010 Via Cimini 13, Calcata (VT)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Podere Rustico",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/155.jpg",
    "address"=> "Viareggio - 55049 Viale dei Tigli",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Appartamento Piazza",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/156.jpg",
    "address"=> "Alghero - 07041 Via Roma",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Nido di Mare",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/157.jpeg",
    "address"=> "Viale Regina Elena, 50, Catania (CT)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Alloggio Cervino",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/158.jpg",
    "address"=> "02020 Via Gran Sasso 30, Filettino (FR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Baita Fienile",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/159.jpg",
    "address"=> "Teramo - 64100 Corso San Giorgio",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Loft Design",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/160.jpg",
    "address"=> "Vercelli - 13100 Corso Libertà",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Residenza Beach",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/161.jpeg",
    "address"=> "Via Lungomare, 190, Siracusa (SR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Rifugio Natura",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/162.jpg",
    "address"=> "03021 Via Rieti 8, Antrodoco (RI)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Country House",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/163.jpg",
    "address"=> "Ercolano - 80056 Corso Resina",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Dimora Elegante",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/164.jpg",
    "address"=> "Caltanissetta - 93100 Corso Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Chalet Maremma",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/165.jpeg",
    "address"=> "Viale Gallipoli, 60, Noto (SR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Chalet Mont Blanc",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/166.jpg",
    "address"=> "04020 Via Simbruini 9, Filettino (FR)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Rustica",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/167.jpg",
    "address"=> "Savona - 17100 Piazza del Popolo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Palazzina Esclusiva",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/168.jpg",
    "address"=> "Trapani - 91100 Via Fardella",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Appartamento Ondine",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/169.jpeg",
    "address"=> "Via Lungomare, 210, Agrigento (AG)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casa Silenzio",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/170.jpg",
    "address"=> "06049 Via Apennini 16, Spello (PG)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Chalet Rustico",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/171.jpg",
    "address"=> "Caserta - 81100 Corso Trieste",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Appartamento Lusso",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/172.jpg",
    "address"=> "Aprilia - 04011 Via dei Prati",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Bungalow Marittimo",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/173.jpeg",
    "address"=> "Lungomare Falcone e Borsellino, 230, Porto Empedocle (AG)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Baita Rustica",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/174.jpg",
    "address"=> "07024 Via Monti di Alghero 22, Nuoro (NU)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Appartamento Vino",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/175.jpg",
    "address"=> "Barletta - 70051 Corso Vittorio Emanuele",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casetta Charme",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/176.jpg",
    "address"=> "Altamura - 70022 Corso Umberto I",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  [
    "name"=> "Loft Riviera",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/177.jpeg",
    "address"=> "Corso Umberto I, 30, Trapani (TP)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Lodge Paradiso",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/178.jpg",
    "address"=> "08022 Via Gennargentu 5, Orosei (NU)",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Casetta Borgo",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/179.jpg",
    "address"=> "Civitavecchia - 00053 Via Aurelia",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "Loft Trendy",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/180.jpg",
    "address"=> "San Severo - 71016 Corso Giacomo Matteotti",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ],
  /*
  [
    "name"=> "nome",
    "description"=> "Casa sulla spiaggia",
    "cover_image"=> "seeder-img/00.jpeg",
    "address"=> "indirizzo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "nome",
    "description"=> "Casale sulla montagna",
    "cover_image"=> "seeder-img/00.jpg",
    "address"=> "indirizzo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "nome",
    "description"=> "Villa di lusso",
    "cover_image"=> "seeder-img/00.jpg",
    "address"=> "indirizzo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [rand(1,17)]
  ],
  [
    "name"=> "nome",
    "description"=> "Appartamento in centro",
    "cover_image"=> "seeder-img/00.jpg",
    "address"=> "indirizzo",
    "address_info"=> "informazioni_sull_indirizzo",
    "price"=> rand(30,150),
    "n_of_bed"=> rand(1,9),
    "n_of_room"=> rand(1,6),
    "n_of_bathroom"=> rand(1,4),
    "apartment_size"=> rand(30,150),
    "visible"=> false,
    "type"=> "tipologia_immobile",
    "sponsor" => [rand(1,3)],
    "services"=> [1,2,5,7]
  ]
  */
];
